import sgqlc.types
import sgqlc.operation
import instrospection_schema

_schema = instrospection_schema
_schema_root = _schema.instrospection_schema

__all__ = ('Operations',)


def query_posts():
    _op = sgqlc.operation.Operation(_schema_root.query_type, name='Posts')
    _op_posts = _op.posts()
    _op_posts.id()
    _op_posts.title()
    _op_posts.body()
    _op_posts.published()
    _op_posts_author = _op_posts.author()
    _op_posts_author.id()
    _op_posts_author.name()
    _op_posts_author.email()
    _op_posts_author.age()
    _op_posts_author_posts = _op_posts_author.posts()
    _op_posts_author_posts.id()
    _op_posts_author_posts.title()
    _op_posts_author_posts.body()
    _op_posts_author_posts.published()
    _op_posts_author_posts_author = _op_posts_author_posts.author()
    _op_posts_author_posts_author.id()
    _op_posts_author_posts_author.name()
    _op_posts_author_posts_author.email()
    _op_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts = _op_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts_author_posts = _op_posts_author_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts_author_posts_author_posts = _op_posts_author_posts_author_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts = _op_posts_author_posts_author_posts_author_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts = _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.age()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts = _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.posts()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.title()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.body()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.published()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author = _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts.author()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.id()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.name()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.email()
    _op_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author_posts_author.age()
    return _op


class Query:
    posts = query_posts()


class Operations:
    query = Query
